serverAddress: "localhost:8090"
database:
  DBHost:        "localhost" 
  #DBHost:        "host.docker.internal"
  DBName:        "postgresdb"
  DBUser:        "postgresadmin"
  DBPass:        "Secret_123" 
  DBPort:        "5432"